typography_spectrum: 0.04877372900955379
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.2613304869737476
  lightness: 0.15090082306414843
  saturation: 0.3619442549534142
  rhythmicContrast: 0.7438527506310493
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5031482155900449
analytics:
  google: null
  facebook: null
  twitter: null
name: aiMade
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Emotional Technology
    id: 9e54cae7-73f5-44c3-bc7a-01d8fd07ebf5
    type: content
  - name: Contact Form
    url: 'http://www.leadershipwithawareness.com/'
    type: external
favicon: null
title: This works
description: Right?
purpose: []
